import {Dimensions, StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    display: 'flex',
    minWidth: Dimensions.get('window').width,
    minHeight: Dimensions.get('window').height,
    backgroundColor: '#ADD4D0',
  },
  formContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    flex: 3,
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    marginHorizontal: 10,
    flex: 2,
  },
  inputGroup: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 10,
  },
  label: {
    display: 'flex',
    fontSize: 16,
    color: 'white',
    width: 120,
    fontFamily: 'averia-libre',
    textAlign: 'right',
    marginRight: 10,
  },
  input: {
    display: 'flex',
    paddingHorizontal: 10,
    backgroundColor: 'white',
    fontFamily: 'averia-libre',
    fontSize: 16,
    width: 240,
    height: 40,
    color: '#3F92C5',
  },
  gender: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: 240,
  },
  genderText: {
    color: 'white',
    fontSize: 18,
  },
  radioGroup: {
    display: 'flex',
    flexDirection: 'row',
    width: 240,
  },
  radioLabel: {
    color: 'white',
    fontSize: 16,
  },
  radioInput: {
    display: 'flex',
    backgroundColor: 'white',
    width: 20,
    height: 20,
    color: '#3F92C5',
    borderRadius: 100,
    marginRight: 10,
  },
  radioInputChecked: {
    display: 'flex',
    backgroundColor: '#419ED7',
    width: 20,
    height: 20,
    color: '#3F92C5',
    borderRadius: 100,
    borderWidth: 2,
    borderColor: 'white',
    marginRight: 10,
  },
  radioInputGroup: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 20,
  },
  buttonGroup: {
    display: 'flex',
    flex: 1,
    justifyContent: 'center',
    width: 140,
  },
  iconCalendar: {
    display: 'flex',
    width: 24,
    height: 24,
  },
  inputCalendar: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    paddingVertical: 10,
    fontFamily: 'averia-libre',
    backgroundColor: 'white',
    borderWidth: 0,
    width: 200,
  },
  labelCalendar: {
    display: 'flex',
    fontSize: 16,
    color: '#3F92C5',
    fontFamily: 'averia-libre',
  },
  errorGroup: {
    display: 'flex',
    alignItems: 'center',
  },
  errorText: {
    color: '#FD7979',
  },
});
