import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    backgroundColor: '#ADD4D0',
    flex: 1,
    padding: 5,
  },
  list: {
    display: 'flex',
    flexDirection: 'column',
    // flex: 1,
    // flexWrap: 'wrap',
  },
  card: {
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#fff',
    borderRadius: 10,
    margin: 5,
    paddingHorizontal: 10,
    paddingTop: 10,
    width: 190,
  },
  searchContainer: {
    display: 'flex',
    flexDirection: 'row',
    margin: 15,
  },
  searchIcon: {
    position: 'absolute',
    width: 20,
    height: 20,
    left: 10,
    top: 8,
    zIndex: 1,
  },
  searchInput: {
    display: 'flex',
    flexDirection: 'row',
    flex: 1,
    fontSize: 16,
    fontFamily: 'averia-libre',
    backgroundColor: '#fff',
    paddingVertical: 5,
    paddingHorizontal: 10,
    textTransform: 'uppercase',
    paddingLeft: 40,
  },
  cardName: {
    fontSize: 24,
    fontFamily: 'averia-libre',
    color: '#3F92C5',
    alignSelf: 'center',
  },
  cardDose: {
    display: 'flex',
    flexDirection: 'row',
    fontSize: 14,
    fontFamily: 'averia-libre',
    color: 'white',
    alignSelf: 'center',
    backgroundColor: '#3F92C5',
    paddingHorizontal: 10,
  },
  cardDate: {
    display: 'flex',
    flexDirection: 'row',
    fontSize: 14,
    fontFamily: 'averia-libre',
    alignSelf: 'center',
    color: '#8B8B8B',
    marginTop: 5,
  },
  cardProof: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 5,
    minHeight: 80,
  },
  cardImageProof: {
    flex: 1,
  },
  nextDateDose: {
    display: 'flex',
    flexDirection: 'row',
    fontSize: 12,
    fontFamily: 'averia-libre',
    alignSelf: 'flex-end',
    color: '#FD7979',
  },
  containerButton: {
    display: 'flex',
    marginTop: 30,
    marginBottom: 50,
    backgroundColor: '#3F92C5',
    width: 140,
    alignSelf: 'center',
  },
  spinner: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 30,
  },
});
