import {Dimensions, StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    display: 'flex',
    backgroundColor: '#ADD4D0',
    flex: 1,
    padding: 5,
    minWidth: Dimensions.get('window').width,
    minHeight: Dimensions.get('window').height,
  },
  formContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    marginTop: 50,
    flex: 1,
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
    marginHorizontal: 10,
  },
  inputGroup: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 10,
  },
  label: {
    display: 'flex',
    fontSize: 16,
    color: 'white',
    width: 140,
    fontFamily: 'averia-libre',
    textAlign: 'right',
    marginRight: 10,
  },
  input: {
    display: 'flex',
    paddingHorizontal: 10,
    backgroundColor: 'white',
    fontFamily: 'averia-libre',
    fontSize: 16,
    width: 235,
    height: 40,
    color: '#3F92C5',
  },
  radioGroup: {
    display: 'flex',
    flexDirection: 'row',
    width: 235,
    flexWrap: 'wrap',
  },
  labelRadio: {
    display: 'flex',
    fontSize: 16,
    color: 'white',
    width: 140,
    fontFamily: 'averia-libre',
    textAlign: 'right',
    marginRight: 10,
    alignSelf: 'flex-start',
  },
  radioLabel: {
    color: 'white',
    fontSize: 16,
    marginBottom: 10,
  },
  radioInput: {
    display: 'flex',
    backgroundColor: 'white',
    width: 20,
    height: 20,
    color: '#3F92C5',
    borderRadius: 100,
    marginRight: 10,
    marginBottom: 10,
  },
  radioInputChecked: {
    display: 'flex',
    backgroundColor: '#419ED7',
    width: 20,
    height: 20,
    color: '#3F92C5',
    borderRadius: 100,
    borderWidth: 2,
    borderColor: 'white',
    marginRight: 10,
    marginBottom: 10,
  },
  radioInputGroup: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 20,
  },
  iconCalendar: {
    display: 'flex',
    width: 24,
    height: 24,
  },
  inputCalendar: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    paddingVertical: 10,
    fontFamily: 'averia-libre',
    backgroundColor: 'white',
    borderWidth: 0,
    width: 180,
  },
  labelCalendar: {
    display: 'flex',
    fontSize: 16,
    color: '#3F92C5',
    fontFamily: 'averia-libre',
  },
  containerButton: {
    display: 'flex',
    width: 140,
    alignSelf: 'center',
    flex: 2,
  },
  labelProof: {
    display: 'flex',
    fontSize: 16,
    color: 'white',
    width: 140,
    fontFamily: 'averia-libre',
    textAlign: 'right',
    marginRight: 10,
    alignSelf: 'flex-start',
  },
  proof: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    minHeight: 140,
  },
  proofButton: {
    display: 'flex',
    width: 200,
  },
  proofImage: {
    display: 'flex',
    marginTop: 10,
    flex: 1,
    minHeight: 110,
  },
  error: {
    display: 'flex',
    color: 'red',
  },
});
